In [5]:
import numpy as np


In [6]:
# Numpy Array(diziler)

In [7]:
listem = [10,20,30,40,50]

In [8]:
myarray = np.array(listem)

In [9]:
myarray

array([10, 20, 30, 40, 50])

In [10]:
type(myarray)

numpy.ndarray

In [11]:
matris = [[10,20,30],[20,30,40],[50,40,60]]

In [12]:
type(matris)

list

In [13]:
np.array(matris)

array([[10, 20, 30],
       [20, 30, 40],
       [50, 40, 60]])

In [14]:
#arange

In [15]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [16]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((7,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

  ## LİNSPACE iki nokta arasında eşit aralık koyarak array oluşturur.

In [19]:
np.linspace(4,10,3)

array([ 4.,  7., 10.])

In [20]:
##EYE

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.randn(8)  #normal dagılam uygun veriler çıkartır.

array([ 1.69152993,  0.01504426, -0.36791847, -0.55423666, -0.44598117,
       -1.14160833,  1.89504657,  0.04456501])

In [23]:
np.random.randn(5,5)

array([[-0.96486266,  1.20690007,  0.96166053, -1.60830101, -1.37234452],
       [-0.29652914,  0.87422538, -0.06466729,  0.48286073,  0.00549067],
       [ 0.9616814 , -0.44463201,  0.80990094, -0.27710464, -0.10510752],
       [ 1.55564704, -0.17567007,  2.25536424,  1.12990221, -0.50226275],
       [ 0.7271607 ,  0.5091223 , -0.7467168 ,  0.21279436, -0.30920187]])

In [24]:
np.random.randint(1,10) #10 hariç tüm degerleri döndürebilir.

6

In [25]:
np.random.randint(1,20,5) #1 den 20 ye rastgele 5 sayı döndürür.

array([ 3, 18,  3, 16,  8])

In [26]:
benimdizi = np.random.randint(10,100,30)

In [27]:
benimdizi

array([79, 70, 36, 95, 79, 68, 33, 49, 74, 29, 54, 11, 49, 54, 92, 63, 88,
       54, 22, 55, 92, 93, 14, 73, 71, 90, 98, 59, 31, 99])

## NUMPY DİZİ METOTLARI