In [1]:
import numpy as np
listem =[[10,20,30],[40,50,60],[70,80,90]]

In [2]:
dizim = np.array(listem)

In [3]:
dizim

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [4]:
dizim[0]

array([10, 20, 30])

In [5]:
dizim[2,2] #birinci satırikinci sütün indexi

90

In [6]:
dizim[1:2,1:2]

array([[50]])

In [7]:
liste = np.arange(50,102,3)

In [8]:
len(liste)

18

In [9]:
mtriks = liste.reshape(6,3)
mtriks

array([[ 50,  53,  56],
       [ 59,  62,  65],
       [ 68,  71,  74],
       [ 77,  80,  83],
       [ 86,  89,  92],
       [ 95,  98, 101]])

In [10]:
mtriks[3,2]

83

In [11]:
mtriks[1:3,2]

array([65, 74])

In [12]:
ebru = np.random.randint(50,500,200)

In [15]:
len(ebru)
ebru

numpy.ndarray

In [16]:
ebruli = ebru.reshape(10,20)
ebruli

array([[189, 208, 185,  68, 290, 305, 223, 365, 341, 249, 311,  70, 107,
        386, 274, 108, 376, 400, 193, 185],
       [275,  80, 201, 394, 200, 317, 308, 369, 284, 238, 266, 474,  61,
        264, 412, 261, 157, 357, 195, 323],
       [339, 105, 413, 104, 362,  91, 253, 451, 301, 242, 236,  85, 202,
         90, 479, 424, 212, 224,  88, 260],
       [452,  84,  85, 172, 241, 129, 463, 474, 258, 239, 315,  73, 365,
        447, 106, 344, 491, 497, 208, 307],
       [433, 188, 289, 439, 240, 252, 488, 414, 373, 151, 261, 204,  71,
         74, 409, 355, 274, 490, 494, 341],
       [432, 352, 299, 253,  64, 191, 112, 311, 191, 436, 114, 488, 260,
        214, 277, 216,  78, 101, 496, 323],
       [ 97, 496, 123,  54, 219, 313, 206, 324, 332, 140, 298, 477, 267,
        150, 346, 305, 476, 216, 238, 128],
       [ 82, 343, 140, 378, 209,  93, 484,  64, 408, 299, 316, 248, 328,
         85,  98, 424, 209, 108, 114,  95],
       [186, 251, 350, 342, 377, 335, 454, 221, 196, 494, 295, 3

In [17]:
ebruli2 = ebruli.copy()

In [18]:
test = ebruli2[5:8,10:15]
test

array([[114, 488, 260, 214, 277],
       [298, 477, 267, 150, 346],
       [316, 248, 328,  85,  98]])

In [19]:
test[:] = 0

In [20]:
ebruli2

array([[189, 208, 185,  68, 290, 305, 223, 365, 341, 249, 311,  70, 107,
        386, 274, 108, 376, 400, 193, 185],
       [275,  80, 201, 394, 200, 317, 308, 369, 284, 238, 266, 474,  61,
        264, 412, 261, 157, 357, 195, 323],
       [339, 105, 413, 104, 362,  91, 253, 451, 301, 242, 236,  85, 202,
         90, 479, 424, 212, 224,  88, 260],
       [452,  84,  85, 172, 241, 129, 463, 474, 258, 239, 315,  73, 365,
        447, 106, 344, 491, 497, 208, 307],
       [433, 188, 289, 439, 240, 252, 488, 414, 373, 151, 261, 204,  71,
         74, 409, 355, 274, 490, 494, 341],
       [432, 352, 299, 253,  64, 191, 112, 311, 191, 436,   0,   0,   0,
          0,   0, 216,  78, 101, 496, 323],
       [ 97, 496, 123,  54, 219, 313, 206, 324, 332, 140,   0,   0,   0,
          0,   0, 305, 476, 216, 238, 128],
       [ 82, 343, 140, 378, 209,  93, 484,  64, 408, 299,   0,   0,   0,
          0,   0, 424, 209, 108, 114,  95],
       [186, 251, 350, 342, 377, 335, 454, 221, 196, 494, 295, 3

In [21]:
ebruli

array([[189, 208, 185,  68, 290, 305, 223, 365, 341, 249, 311,  70, 107,
        386, 274, 108, 376, 400, 193, 185],
       [275,  80, 201, 394, 200, 317, 308, 369, 284, 238, 266, 474,  61,
        264, 412, 261, 157, 357, 195, 323],
       [339, 105, 413, 104, 362,  91, 253, 451, 301, 242, 236,  85, 202,
         90, 479, 424, 212, 224,  88, 260],
       [452,  84,  85, 172, 241, 129, 463, 474, 258, 239, 315,  73, 365,
        447, 106, 344, 491, 497, 208, 307],
       [433, 188, 289, 439, 240, 252, 488, 414, 373, 151, 261, 204,  71,
         74, 409, 355, 274, 490, 494, 341],
       [432, 352, 299, 253,  64, 191, 112, 311, 191, 436, 114, 488, 260,
        214, 277, 216,  78, 101, 496, 323],
       [ 97, 496, 123,  54, 219, 313, 206, 324, 332, 140, 298, 477, 267,
        150, 346, 305, 476, 216, 238, 128],
       [ 82, 343, 140, 378, 209,  93, 484,  64, 408, 299, 316, 248, 328,
         85,  98, 424, 209, 108, 114,  95],
       [186, 251, 350, 342, 377, 335, 454, 221, 196, 494, 295, 3

In [22]:
ebruli[[-1,-2,-3]] #fansiy index havalı indexleme 

array([[157, 331, 108, 292,  70, 119, 122, 425, 116, 242, 329, 158, 175,
        132, 280, 261,  79, 498, 243, 441],
       [186, 251, 350, 342, 377, 335, 454, 221, 196, 494, 295, 375, 444,
        306, 380, 178, 275,  93,  75, 194],
       [ 82, 343, 140, 378, 209,  93, 484,  64, 408, 299, 316, 248, 328,
         85,  98, 424, 209, 108, 114,  95]])