In [1]:
import numpy as np

In [2]:
dizi = np.arange(2,19,3)

In [4]:
dizi.shape
dizi

array([ 2,  5,  8, 11, 14, 17])

In [4]:
matris = dizi.reshape(3,2)

In [5]:
matris

array([[ 2,  5],
       [ 8, 11],
       [14, 17]])

In [6]:
dizi[3]

11

In [7]:
matris

array([[ 2,  5],
       [ 8, 11],
       [14, 17]])

In [8]:
dizi

array([ 2,  5,  8, 11, 14, 17])

In [9]:
dizi[2:4]= -7

In [10]:
dizi

array([ 2,  5, -7, -7, 14, 17])

In [11]:
yeniDizi = np.arange(0,17,2)

In [12]:
yeniDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [13]:
ikinciDizi= yeniDizi[3:6]

In [14]:
ikinciDizi[:] =500

In [15]:
ikinciDizi

array([500, 500, 500])

In [16]:
 yeniDizi

array([  0,   2,   4, 500, 500, 500,  12,  14,  16])

In [17]:
## Burada array larda yapılan değişikleri tüm listeyi de etkiler.
## Görünürde oluşturdumz dizi de yaptıgımz değişkler arraylaraı da etkiler. 

In [18]:
#Yapılan işlemleri asıl diziyi etkilemesini istemiyorsak, kopyasını oluşturur
# sonra kopya üzerinde çalışırz.

In [19]:
dizi = np.arange(0,22,2)

In [20]:
copyadizi = dizi.copy()

In [21]:
copyadizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
dizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
newdizi= copyadizi[3:9]

In [24]:
newdizi[:] = 150

In [25]:
newdizi

array([150, 150, 150, 150, 150, 150])

In [26]:
copyadizi

array([  0,   2,   4, 150, 150, 150, 150, 150, 150,  18,  20])

In [27]:
dizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])