In [4]:
import numpy as np

In [5]:
liste = np.random.randint(1,99,20)

In [14]:
liste

array([42, 66, 24, 49, 37, 40, 63, 45, 95, 29,  2, 29, 83, 76, 92, 80, 14,
       73, 77, 78])

In [15]:
np.shape(liste)

(20,)

In [16]:
matriks = liste.reshape(5,4)

In [17]:
matriks

array([[42, 66, 24, 49],
       [37, 40, 63, 45],
       [95, 29,  2, 29],
       [83, 76, 92, 80],
       [14, 73, 77, 78]])

In [18]:
deger = matriks <25

In [19]:
deger

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [20]:
matriks[deger] # MATRİKS DE TRUE OLANLARI GÖSTERMİŞ OLDUK.

array([24,  2, 14])

In [21]:
matriks[matriks<25] #bu da alternatif gösterim.

array([24,  2, 14])

In [22]:
matriks[15<matriks]

array([42, 66, 24, 49, 37, 40, 63, 45, 95, 29, 29, 83, 76, 92, 80, 73, 77,
       78])

In [23]:
matiks +100

NameError: name 'matiks' is not defined

In [24]:
matriks +100

array([[142, 166, 124, 149],
       [137, 140, 163, 145],
       [195, 129, 102, 129],
       [183, 176, 192, 180],
       [114, 173, 177, 178]])

In [25]:
matriks **2

array([[1764, 4356,  576, 2401],
       [1369, 1600, 3969, 2025],
       [9025,  841,    4,  841],
       [6889, 5776, 8464, 6400],
       [ 196, 5329, 5929, 6084]], dtype=int32)

In [26]:
matriks/100

array([[0.42, 0.66, 0.24, 0.49],
       [0.37, 0.4 , 0.63, 0.45],
       [0.95, 0.29, 0.02, 0.29],
       [0.83, 0.76, 0.92, 0.8 ],
       [0.14, 0.73, 0.77, 0.78]])

In [27]:
matriks

array([[42, 66, 24, 49],
       [37, 40, 63, 45],
       [95, 29,  2, 29],
       [83, 76, 92, 80],
       [14, 73, 77, 78]])

In [28]:
matriks %2

array([[0, 0, 0, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 1, 0]], dtype=int32)

In [29]:
matriks%3

array([[0, 0, 0, 1],
       [1, 1, 0, 0],
       [2, 2, 2, 2],
       [2, 1, 2, 2],
       [2, 1, 2, 0]], dtype=int32)

In [30]:
matriks - matriks

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
matriks/matriks

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.sqrt(matriks) #karekok alma fonksiyonu

array([[6.4807407 , 8.1240384 , 4.89897949, 7.        ],
       [6.08276253, 6.32455532, 7.93725393, 6.70820393],
       [9.74679434, 5.38516481, 1.41421356, 5.38516481],
       [9.11043358, 8.71779789, 9.59166305, 8.94427191],
       [3.74165739, 8.54400375, 8.77496439, 8.83176087]])